name: ✨ New Extension Request
description: Request/Suggest any extension you think is missing
title: "Title: "
labels: "Extension Request"
body:
  - type: textarea #description
    attributes:
      label: Is your extension request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea #solution
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
      placeholder: Kindly elaborate.
    validations:
      required: true

  - type: textarea #alternatives
    attributes:
      label: Describe alternatives you've considered.
      description: A clear and concise description of any alternative solution or feature you have considered.
      placeholder: Type here.
    validations:
      required: true

  - type: textarea #Additional Context
    attributes:
      label: Add any other context or screenshots about the extension here.
      description: Any miscellaneous suggestions you'd like to give.
